# Generated by Django 4.1.5 on 2023-02-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create',
            new_name='created',
        ),
        migrations.AddField(
            model_name='review',
            name='dept',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.TextField(max_length=250),
        ),
    ]
