# Generated by Django 4.1.5 on 2023-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_difficult_review_fun_review_interesting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='difficult',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='interesting',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
