# Generated by Django 4.1.5 on 2023-02-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_rename_create_review_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptCode', models.CharField(max_length=10)),
                ('deptName', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='classCode',
        ),
        migrations.RemoveField(
            model_name='review',
            name='className',
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=10)),
                ('className', models.CharField(max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.department')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.course'),
        ),
    ]
