# Generated by Django 4.1.5 on 2023-02-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_course_department_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dept',
        ),
    ]
