# Generated by Django 4.1.5 on 2023-02-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_course_course_dept_remove_review_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classCode',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='className',
            new_name='courseName',
        ),
    ]
