# Generated by Django 4.1.5 on 2023-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_classcode_course_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.TextField(max_length=800),
        ),
    ]
